export const toolCatalog = [
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    color: "bg-slate-800",
    symbol: "↘",
    accept: ".pdf",
    multiple: true,
    supported: true,
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    color: "bg-slate-700",
    symbol: "↙",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    color: "bg-slate-600",
    symbol: "⇲",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Extract PDF text into DOCX format.",
    color: "bg-slate-700",
    symbol: "W",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Extract PDF text into PPTX slides.",
    color: "bg-zinc-700",
    symbol: "P",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract PDF text lines into XLSX sheets.",
    color: "bg-gray-700",
    symbol: "X",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOC or DOCX files into PDF.",
    color: "bg-slate-700",
    symbol: "W",
    accept: ".doc,.docx",
    multiple: false,
    supported: true,
  },
  {
    slug: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Convert PPT or PPTX files into PDF.",
    color: "bg-zinc-700",
    symbol: "P",
    accept: ".ppt,.pptx",
    multiple: false,
    supported: true,
  },
  {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert XLS or XLSX files into PDF.",
    color: "bg-gray-700",
    symbol: "X",
    accept: ".xls,.xlsx",
    multiple: false,
    supported: true,
  },
  {
    slug: "edit-pdf",
    title: "Edit PDF",
    description: "Apply a simple text overlay edit to your PDF.",
    color: "bg-neutral-700",
    symbol: "✎",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert each PDF page into JPG images.",
    color: "bg-stone-700",
    symbol: "J",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert image files into one PDF.",
    color: "bg-stone-700",
    symbol: "JPG",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    supported: true,
  },
  {
    slug: "sign-pdf",
    title: "Sign PDF",
    description: "Place a text signature on the document.",
    color: "bg-[#5d86bf]",
    symbol: "✍",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "watermark",
    title: "Watermark",
    description: "Stamp text over your PDF pages.",
    color: "bg-neutral-700",
    symbol: "⚑",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate pages by 90, 180, or 270 degrees.",
    color: "bg-neutral-700",
    symbol: "↻",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert HTML files into PDF.",
    color: "bg-stone-700",
    symbol: "HTML",
    accept: ".html,.htm",
    multiple: false,
    supported: true,
  },
  {
    slug: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password security from the PDF.",
    color: "bg-[#5d86bf]",
    symbol: "🔓",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "protect-pdf",
    title: "Protect PDF",
    description: "Add password security to the PDF.",
    color: "bg-[#5d86bf]",
    symbol: "🛡",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "organize-pdf",
    title: "Organize PDF",
    description: "Reorder pages with a page-order string like 1,3,2,4.",
    color: "bg-zinc-700",
    symbol: "A",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Rewrite the PDF into an archival-style output.",
    color: "bg-[#5d86bf]",
    symbol: "/A",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "repair-pdf",
    title: "Repair PDF",
    description: "Try to rebuild damaged PDFs by rewriting pages.",
    color: "bg-slate-600",
    symbol: "🛠",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "page-numbers",
    title: "Page numbers",
    description: "Add page numbers to each page.",
    color: "bg-neutral-700",
    symbol: "1 2",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "scan-to-pdf",
    title: "Scan to PDF",
    description: "Create a PDF from scanned image files.",
    color: "bg-slate-700",
    symbol: "▣",
    accept: ".jpg,.jpeg,.png,.webp",
    multiple: true,
    supported: true,
  },
  {
    slug: "ocr-pdf",
    title: "OCR PDF",
    description: "Extract text from PDF pages or images and generate an OCR-enabled PDF.",
    color: "bg-slate-600",
    symbol: "OCR",
    accept: ".pdf,.jpg,.jpeg,.png",
    multiple: false,
    supported: true,
  },
  {
    slug: "compare-pdf",
    title: "Compare PDF",
    description: "Compare the extracted text of two PDFs.",
    color: "bg-[#5d86bf]",
    symbol: "▥",
    accept: ".pdf",
    multiple: true,
    supported: true,
  },
  {
    slug: "redact-pdf",
    title: "Redact PDF",
    description: "Apply a simple visual redaction band to the page.",
    color: "bg-[#5d86bf]",
    symbol: "▤",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "crop-pdf",
    title: "Crop PDF",
    description: "Crop margins from the document.",
    color: "bg-neutral-700",
    symbol: "⌗",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "ai-summarizer",
    title: "AI Summarizer",
    description: "Create a heuristic summary from extracted text.",
    color: "bg-[#6b4de6]",
    symbol: "✦",
    badge: "New!",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "translate-pdf",
    title: "Translate PDF",
    description: "Extract and translate PDF text into a translated PDF document.",
    color: "bg-[#6b4de6]",
    symbol: "文",
    badge: "New!",
    accept: ".pdf",
    multiple: false,
    supported: true,
  },
  {
    slug: "create-workflow",
    title: "Create a workflow",
    description: "Run multiple tool processors in sequence from one workflow request.",
    special: "workflow",
    supported: true,
    accept:
      ".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.html,.htm",
    multiple: true,
  },
];

export const commonNavTools = [
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "convert-pdf",
  "all-pdf-tools",
];

export const toolBySlug = Object.fromEntries(
  toolCatalog.map((tool) => [tool.slug, tool]),
);
